### ISSUE TITLE
获得指定用户的所有关注者

### ISSUE THREAD

**Issue by bcd6** [simon300000/bili-api#15]
请问目前有这个功能吗，router里好像没找到，如果没有，可否添加一下，谢谢！

**Comment by simon300000** [comment]
这个功能挺好的，但是我也无能为力，因为B站限制，只能访问关注者的前5页
所以我不能获取所有关注者，但是前5页还是可以的www

**Comment by bcd6** [comment]
好吧，谢谢回复。
最近在重构之前的b站爬虫项目，偶然发现这个api，用起来还是挺方便的。
不过关键功能看来还是只能自己解析html了。

**Comment by simon300000** [comment]
如果有什么功能需求，请务必和我说！
这个也是给我自己的爬虫写的，所以功能肯定有一定局限性
但是大部分功能扩展应该是挺简单的
（需要登录的部分不行www）

**Comment by bcd6** [comment]
跑去看了一眼b站，获取关注的接口好像是这个
https://api.bilibili.com/x/relation/followings?vmid=6805565&pn=4&ps=20&order=desc&jsonp=jsonp&callback=__jp35，
请问你怎么判断只能抓前5页的？
感觉好像可以通过设置一个cookie请求头解决。

**Comment by simon300000** [comment]
不大清楚哎
这个URL写简单了是
https://api.bilibili.com/x/relation/followings?vmid=6805565&pn=4&ps=20
经过我的测试，似乎pn大于5的时候就会返回错误

https://api.bilibili.com/x/relation/followings?vmid=6805565&pn=6&ps=20
```json
{"code":22007,"message":"限制只访问前5页","ttl":1}
```

https://api.bilibili.com/x/relation/followings?vmid=6805565&pn=1&ps=100
然而把ps设置的大于50也只会每一页50个
<img width="685" alt="image" src="https://user-images.githubusercontent.com/12656264/64906167-1af9a780-d6e3-11e9-971f-5184cfeae7e2.png">

所以似乎只能获取250的关注者

**Comment by simon300000** [comment]
不过对于关注小于250的用户来说的确可以获得所有关注，的确可以加进来www

**Comment by bcd6** [comment]
好吧，似乎问了个傻问题，感谢配图。
自己测试了下，传入COOKIE header可行。
如果api可以添加一个 cookie option ，让调用者自己决定是否传入，应该可以大大扩展受登录限制的部分。
b站的cookie 应该是有一个月有效期，还是有一点使用价值的。

**Comment by simon300000** [comment]
奇怪了，我在浏览器打开的，为什么没有cookie呢...
这个功能可以加www

**Comment by simon300000** [comment]
啊，大概只有自己的cookie才行

**Comment by bcd6** [comment]
好像不是每个请求都有，我找到的是这样的
Cookie: fts=xxx; sid=xxx; LIVE_BUVID=xxx; UM_distinctid=xxxx; ...... bili_jct=xxxxx
里面有好多字段，具体不清楚是哪些起作用，不过我都传进去了（用postman工具请求，不是直接通过浏览器打开）。
只要有了cookie，就相当于你已经登录了，理论上浏览器上支持的，都可以通过api操作了

**Comment by simon300000** [comment]
看起来，似乎必须要我自己的cookie才能看我自己的全部粉丝...

**Comment by bcd6** [comment]
好吧，发现了，
![image](https://user-images.githubusercontent.com/2210053/64906385-24fac500-d73a-11e9-960e-f0a4b755e415.png)
查看别人的数据，确实是被限制了。
不过我是用来查自己的数据，所以还好orz。

**Comment by simon300000** [comment]
我发了一个新版本
```javascript
const biliAPI = require('.')

const SESSDATA = /* 你的Cookie里的SESSDATA */

biliAPI({ mid: 3499295, SESSDATA }, ['allFollowers'], { wait: 200 }).then(({ allFollowers }) => {
  console.log(allFollowers)
  console.log(allFollowers.length)
})
```

理论上能通过这个cookie获取所有关注者

我这里测试可以正常工作www

**Comment by simon300000** [comment]
本来我想实现输入用户名密码自动登录的，但是登陆验证不知道怎么搞于是放弃

**Comment by simon300000** [comment]
@bcd6 我现在实现了allFollowers这个功能
https://github.com/simon300000/bili-api/commit/940006144f7db9fc345a32c3435c762367a35ff0

输入Cookie获取所有关注者:
https://github.com/simon300000/bili-api/commit/133b5b074005594f72a2e5de5ddd4de9dc546764

欢迎尝试www
