### ISSUE TITLE
用户信息API失效了?

### ISSUE THREAD

**Issue by fzxiao233** [simon300000/bili-api#5]
现在访问给的是默认错误页面，B站关闭API了？

**Comment by simon300000** [comment]
哎？哪个出问题了？

**Comment by fzxiao233** [comment]
貌似访问用户信息的都有问题，比如[https://api.bilibili.com/x/relation/stat?vmid=349991143]

**Comment by simon300000** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12656264/56427061-0f00e980-62ed-11e9-9ee8-7fa3f7a35fbc.png">
我这里完全正常的说？

**Comment by simon300000** [comment]
Bilibili似乎有一个放爆破系统，要是你持续用了哪个API频率过高（一秒超过好几次）会被Ban一段时间，会不会是因为这个？

**Comment by simon300000** [comment]
试试看4G什么的，可能会好

**Comment by fzxiao233** [comment]
啊，我这刚刚还是页面不存在，现在也正常了，
应该不是爆破的问题=A=，因为我才访问了一次

**Comment by fzxiao233** [comment]
这货怎么时好时坏的，刷新一下就又不存在的=A=，看来是B站的锅

**Comment by simon300000** [comment]
嗯，大概是B站的锅→_→
时好时坏我怀疑有可能是浏览器缓存的问题？
