### ISSUE TITLE
动态API+紧跟时事

### ISSUE THREAD

**Issue by Metric-Void** [simon300000/bili-api#78]
1. 例子是hololive... 嗯，换掉吧。
2. Bilibili有公开的动态接口：https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=${mid}&offset_dynamic_id=0&need_top=0&platform=web ，希望能试着整合一下。（我自己正好有需求，也在试着弄）

**Comment by Metric-Void** [comment]
ps. 这个接口不是专门动态，是个人主页的，会返回一个巨大的json。data.cards[].card里面是一个json字符串，表示动态，然后底下的offset提供分段。

**Comment by simon300000** [comment]
好我研究研究

**Comment by simon300000** [comment]
不过我最近有点忙哦，可能不会很快弄好

**Comment by Metric-Void** [comment]
写好了！

Fork在这里 https://github.com/Metric-Void/bili-api

没有写test（动态内容总是在变 怎么测呢），但是写了example。

**Comment by Metric-Void** [comment]
另：所有的examples/似乎都是require('bili-api')的，也就是说会基于发行版的文件。也许基于目前本地的文件更合理一些？使用require('../'); 之类

**Comment by Metric-Void** [comment]
#80

**Comment by simon300000** [comment]
我看看 我看看
